CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    username VARCHAR(225)NOT NULL, 
    email VARCHAR(225) UNIQUE NOT NULL,
    gender CHAR(1) NOT NULL,
    password VARCHAR(225)
    );


CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    title VARCHAR(225) UNIQUE NOT NULL,  
    author VARCHAR(225) NOT NULL,  
    overview VARCHAR(225),
    categoryId INT,
    userId INT,

    FOREIGN KEY (userId) 
    REFERENCES users(id) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE,

    FOREIGN KEY (categoryId)
    REFERENCES book_categories(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS book_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(225) UNIQUE NOT NULL,
);